# Generated by Django 5.2.6 on 2025-09-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reservation_time",
            field=models.DateTimeField(null=True),
        ),
    ]
