# Generated by Django 5.2.6 on 2025-09-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_reservation_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "permissions": [
                    ("change_order_status", "Can change order status"),
                    ("view_all_orders", "Can view all orders (bypass ownership)"),
                ]
            },
        ),
    ]
