services:
  db:
    image: postgres:16.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432" # for dev only
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE

  web:
    build: .
    container_name: canteen_ms
    image: canteen-django:dev
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: ./apps
          target: /app/apps

        - action: sync
          path: ./config
          target: /app/config

        - action: rebuild
          path: ./uv.lock

        - action: rebuild
          path: ./pyproject.toml

        - action: rebuild
          path: ./Dockerfile
    networks:
      - public

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro # additional config files
      - ./certbot/conf:/etc/nginx/ssl:ro # SSL certificates
      - ./certbot/www:/var/www/certbot:ro # Let's Encrypt challenges
    depends_on:
      - web
    networks:
      - public

volumes:
  postgres_data:

networks:
  public:
