services:
  db:
    image: postgres:16.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.prod
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE
    networks:
      - private

  web:
    # pull image instead of build
    build: .
    container_name: canteen_ms
    image: canteen-django:dev
    env_file: .env.prod
    command:
      - /scripts/start-django-prod.sh
    depends_on:
      db:
        condition: service_started
    networks:
      - public
      - private
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro # additional config files
      - ./certbot/conf:/etc/ssl:ro # SSL certificates
      - ./certbot/www:/var/www/certbot:ro # Let's Encrypt challenges
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web
    networks:
      - public

volumes:
  postgres_data:
  static_volume:

networks:
  public:
  private:
