# Generated by Django 5.2.6 on 2025-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("staff", "Staff"),
                    ("admin", "Administrator"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
