# Generated by Django 5.2.6 on 2025-09-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('totp', 'Authenticator')], max_length=20, null=True),
        ),
    ]
