# Generated by Django 5.2.6 on 2025-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_mfa_enabled_user_mfa_secret_user_mfa_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, null=True),
        ),
    ]
