# Generated by Django 5.2.6 on 2025-11-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_provider',
            field=models.CharField(choices=[('none', 'None'), ('microsoft', 'Microsoft')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
