# Generated by Django 5.2.6 on 2025-09-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balance",
            options={
                "permissions": [
                    ("credit_balance", "Can credit a user's balance"),
                    ("debit_balance", "Can debit a user's balance"),
                    ("view_all_balances", "Can view all user balances"),
                    ("view_own_balance", "Can view own balance"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("refund_payment", "Can create a refund for a payment"),
                    ("view_all_transactions", "Can view all transactions"),
                    ("view_own_transaction", "Can view own transactions"),
                ],
            },
        ),
    ]
