# Generated by Django 5.2.6 on 2025-09-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_alter_balance_options_alter_transaction_options"),
    ]

    operations = []
