# Generated by Django 5.2.6 on 2025-09-10 21:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "category",
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="menus.category",
                    ),
                ),
            ],
            options={
                "db_table": "item",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
            options={
                "db_table": "menu",
                "indexes": [
                    models.Index(fields=["start_time"], name="menu_start_t_a6c32c_idx"),
                    models.Index(fields=["end_time"], name="menu_end_tim_623728_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "override_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_permanent", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        db_column="item_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="menu_items",
                        to="menus.item",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        db_column="menu_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="menus.menu",
                    ),
                ),
            ],
            options={
                "db_table": "menu_item",
                "ordering": ["menu", "display_order"],
            },
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["category"], name="item_categor_33fe10_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["name"], name="item_name_83d1f6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("category", "name")},
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["menu", "display_order"], name="menu_item_menu_id_2debaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["item"], name="menu_item_item_id_dada29_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="menuitem",
            unique_together={("menu", "item")},
        ),
    ]
