# Generated by Django 5.2.6 on 2025-09-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="items",
            field=models.ManyToManyField(
                related_name="menus",
                related_query_name="menu",
                through="menus.MenuItem",
                through_fields=("menu", "item"),
                to="menus.item",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="override_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
