# Generated by Django 5.2.6 on 2025-09-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("display_order", "name"),
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["menu", "display_order"],
                "permissions": [
                    ("change_menuitem_price", "Can set override price on a menu item"),
                    (
                        "change_menuitem_quantity",
                        "Can change available quantity on a menu item",
                    ),
                    ("set_menuitem_permanent", "Can mark a menu item as permanent"),
                ],
            },
        ),
        migrations.RenameIndex(
            model_name="menuitem",
            new_name="menu_item_menu_433d17_idx",
            old_name="menu_item_menu_id_2debaa_idx",
        ),
        migrations.RenameIndex(
            model_name="menuitem",
            new_name="menu_item_item_6c5f6e_idx",
            old_name="menu_item_item_id_dada29_idx",
        ),
        migrations.AddField(
            model_name="menu",
            name="items",
            field=models.ManyToManyField(
                related_name="menus",
                related_query_name="menu",
                through="menus.MenuItem",
                through_fields=("menu", "item"),
                to="menus.item",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                ],
                default="breakfast",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="item",
            field=models.ForeignKey(
                db_column="item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="menu_items",
                to="menus.item",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                db_column="menu",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="menus.menu",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="override_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
