# Generated by Django 5.2.6 on 2025-09-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_menu_items_alter_menuitem_override_price"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="menuitem",
            new_name="menu_item_menu_433d17_idx",
            old_name="menu_item_menu_id_2debaa_idx",
        ),
        migrations.RenameIndex(
            model_name="menuitem",
            new_name="menu_item_item_6c5f6e_idx",
            old_name="menu_item_item_id_dada29_idx",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="item",
            field=models.ForeignKey(
                db_column="item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="menu_items",
                to="menus.item",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                db_column="menu",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="menus.menu",
            ),
        ),
    ]
