# Generated by Django 5.2.6 on 2025-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_alter_category_options_alter_menuitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="override_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
