# Generated by Django 5.2.6 on 2025-09-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_rename_menu_item_menu_id_2debaa_idx_menu_item_menu_433d17_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=20),
            preserve_default=False,
        ),
    ]
