# Generated by Django 5.2.6 on 2025-09-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "menus",
            "0003_rename_menu_item_menu_id_2debaa_idx_menu_item_menu_433d17_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["menu", "display_order"],
                "permissions": [
                    ("change_menuitem_price", "Can set override price on a menu item"),
                    (
                        "change_menuitem_quantity",
                        "Can change available quantity on a menu item",
                    ),
                    ("set_menuitem_permanent", "Can mark a menu item as permanent"),
                ],
            },
        ),
    ]
